development:
  adapter: postgresql
  encoding: unicode
  database: p_development
  pool: 5
  username: nirmala
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: post_test
  pool: 5
  username: nirmala
  password: 123456